/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KantuTest {
    @Test 
    void countKantuTest() {
        Kantu demoKantu = new Kantu();
        demoKantu.addHai("i-wan", 1);
        demoKantu.addHai("i--wan", 1);
        demoKantu.addHai("i---wan", 1);
        demoKantu.addHai("i----wan", 1);
        demoKantu.countMentu(demoKantu.getHai());
        int oneKantu = 1;
        assertEquals(oneKantu, demoKantu.getCountKantu());
    }
}
