/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KotuTest {
    /**
     * 刻子の数がしっかりと数えられているのか検証
     * 検証手順
     * (1)Kotuクラスの空のHashMapを準備して、それに同じ値の牌を3つ追加する。
     * (2)刻子の数を調べると刻子が1つとなるはず。これを検証する。
     */
    @Test 
    void countKotuTest() {
        Kotu demoKotu = new Kotu();
        demoKotu.addHai("i-wan", 1);
        demoKotu.addHai("i--wan",1);
        demoKotu.addHai("i---wan", 1);
        demoKotu.countMentu(demoKotu.getHai());
        int oneKotu = 1;
        assertEquals(oneKotu, demoKotu.getCountKotu());
    }
}
