/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SyuntuTest {
    /**
     * 順子の数がしっかりと数えられているのか検証
     * 検証手順
     * (1)Syuntuクラスの空のHashMapを準備して、それに連続した値の牌を3つ追加する。
     * (2)順子の数を調べると順子が1つとなるはず。これを検証する。
     */
    @Test 
    void countSyuntuTest() {
        Syuntu demoSyuntu = new Syuntu();
        demoSyuntu.addHai("i-wan", 1);
        demoSyuntu.addHai("ryan-wan", 2);
        demoSyuntu.addHai("san-wan", 3);
        demoSyuntu.countMentu(demoSyuntu.getHai());
        int oneSyuntu = 1;
        assertEquals(oneSyuntu, demoSyuntu.getCountSyuntu());
    }
}
