/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SyuntuTest {
    @Test 
    void countSyuntuTest() {
        Syuntu demoSyuntu = new Syuntu(0);
        demoSyuntu.addHai("i-wan", 1);
        demoSyuntu.addHai("ryan-wan", 2);
        demoSyuntu.addHai("san-wan", 3);
        demoSyuntu.countMentu(demoSyuntu.getHai());
        int oneSyuntu = 1;
        assertEquals(oneSyuntu, demoSyuntu.getCountSyuntu());
    }
}
