/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TehaiTest {
    @Test 
    void tehaisuuTest(){
        int defaultTehaisuu = 14;
        Tehai demoTehai = new Tehai("東家");
        demoTehai.addTehai("i-wan", 1);
        demoTehai.addTehai("ryan-wan", 2);
        demoTehai.addTehai("san-wan", 3);
        assertNotEquals(defaultTehaisuu, demoTehai.getHai().size());
    }
}
    