/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ZyantouTest {
    @Test 
    void countZyantouTest() {
        Zyantou demoZyantou = new Zyantou(0,0,0);
        demoZyantou.addHai("i-wan", 1);
        demoZyantou.addHai("i--wan",1);
        demoZyantou.countMentu(demoZyantou.getHai());
        int oneZyantou = 1;
        assertEquals(oneZyantou, demoZyantou.getCountZyantou());
    }
}
