/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215716;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ZyantouTest {
    /**
     * 雀頭の数がしっかりと数えられているのか検証
     * 検証手順
     * (1)Zyantouクラスの空のHashMapを準備して、それに同じ値の牌をふ2つ追加する。
     * (2)雀頭の数を調べると雀頭が1つとなるはず。これを検証する。
     */
    @Test 
    void countZyantouTest() {
        Zyantou demoZyantou = new Zyantou();
        demoZyantou.addHai("i-wan", 1);
        demoZyantou.addHai("i--wan",1);
        demoZyantou.countMentu(demoZyantou.getHai());
        int oneZyantou = 1;
        assertEquals(oneZyantou, demoZyantou.getCountZyantou());
    }
}
